"""add_role_and_is_active_to_user

Revision ID: 1fd78e4cb1ac
Revises: bc31ffa87c33
Create Date: 2026-06-19 04:21:09.480144

"""

from typing import Sequence, Union

import sqlalchemy as sa

# Імпортуємо специфічний для PostgreSQL модуль для роботи з ENUM
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fd78e4cb1ac"
down_revision: Union[str, Sequence[str], None] = "bc31ffa87c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Вручну створюємо тип ENUM в базі даних PostgreSQL перед додаванням колонки
    user_role_enum = postgresql.ENUM("USER", "ADMIN", name="userrole")
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # 2. Додаємо колонки (твій автогенерований код)
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="userrole"),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Спочатку видаляємо колонки з таблиці
    op.drop_column("users", "role")
    op.drop_column("users", "is_active")

    # 2. Вручну видаляємо сам тип ENUM з бази даних PostgreSQL
    user_role_enum = postgresql.ENUM("USER", "ADMIN", name="userrole")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
